#!/usr/bin/env python3
"""Generate a secret-safe Tencent Cloud .env.production for FitHub."""

from __future__ import annotations

import argparse
import os
import secrets
import sys
import urllib.parse
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import tencent_cloud_preflight


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = ROOT / "deploy" / "tencent-cloud" / ".env.production"
DEFAULT_NGINX_OUTPUT = ROOT / "deploy" / "tencent-cloud" / "nginx-fithub.conf"
NGINX_TEMPLATE = ROOT / "deploy" / "tencent-cloud" / "nginx-fithub.conf.example"


def generate_token() -> str:
    return secrets.token_urlsafe(36)


def normalize_origin(value: str) -> str:
    parsed = urllib.parse.urlparse(str(value or "").strip().rstrip("/"))
    host = (parsed.hostname or "").lower()
    if parsed.scheme != "https" or not host:
        raise ValueError("API 域名必须是完整 HTTPS 地址，例如 https://api.example.cn")
    if parsed.path and parsed.path != "/":
        raise ValueError("API 域名只填写 origin，不要带 /api 或其它路径。")
    return urllib.parse.urlunparse((parsed.scheme, parsed.netloc, "", "", "", ""))


def build_env_values(
    *,
    api_origin: str,
    supabase_url: str,
    supabase_service_role_key: str,
    admin_token: str = "",
    media_maintenance_token: str = "",
    media_bucket: str = "fithub-media",
    media_storage_provider: str = "supabase",
    cos_secret_id: str = "",
    cos_secret_key: str = "",
    cos_region: str = "",
    cos_bucket: str = "",
    cos_public_base_url: str = "",
) -> dict[str, str]:
    provider = str(media_storage_provider or "supabase").strip().lower()
    values = {
        "PORT": "10000",
        "FITHUB_URL_PREFIX": "/",
        "FITHUB_DATA_DIR": "/data/fithub",
        "FITHUB_PUBLIC_API_ORIGIN": normalize_origin(api_origin),
        "SUPABASE_URL": str(supabase_url or "").strip().rstrip("/"),
        "SUPABASE_SERVICE_ROLE_KEY": str(supabase_service_role_key or "").strip(),
        "FITHUB_SUPABASE_TABLE": "fithub_app_state",
        "FITHUB_SUPABASE_ROW_ID": "primary",
        "FITHUB_SUPABASE_TIMEOUT": "8",
        "FITHUB_SUPABASE_REFRESH_COOLDOWN_SECONDS": "30",
        "FITHUB_SUPABASE_BACKUP_RETENTION": "96",
        "FITHUB_SUPABASE_PRUNE_INTERVAL_SECONDS": "3600",
        "FITHUB_MEDIA_STORAGE_PROVIDER": provider,
        "FITHUB_MEDIA_BUCKET": media_bucket,
        "FITHUB_TENCENT_COS_SECRET_ID": str(cos_secret_id or "").strip(),
        "FITHUB_TENCENT_COS_SECRET_KEY": str(cos_secret_key or "").strip(),
        "FITHUB_TENCENT_COS_REGION": str(cos_region or "").strip(),
        "FITHUB_TENCENT_COS_BUCKET": str(cos_bucket or "").strip(),
        "FITHUB_TENCENT_COS_PUBLIC_BASE_URL": normalize_origin(cos_public_base_url) if cos_public_base_url else "",
        "FITHUB_IMAGE_UPLOAD_LIMIT_BYTES": "10485760",
        "FITHUB_VIDEO_UPLOAD_LIMIT_BYTES": "8388608",
        "FITHUB_THUMB_UPLOAD_LIMIT_BYTES": "2097152",
        "FITHUB_ADMIN_TOKEN": admin_token or generate_token(),
        "FITHUB_MEDIA_MAINTENANCE_TOKEN": media_maintenance_token or generate_token(),
    }
    failures: list[str] = []
    tencent_cloud_preflight.validate_env(values, failures)
    if failures:
        raise ValueError("; ".join(failures))
    return values


def render_env(values: dict[str, str]) -> str:
    lines = [
        "# FitHub Tencent Cloud production environment.",
        "# Generated by scripts/init_tencent_env.py. Do not commit this file.",
        "",
    ]
    for key in (
        "PORT",
        "FITHUB_URL_PREFIX",
        "FITHUB_DATA_DIR",
        "FITHUB_PUBLIC_API_ORIGIN",
        "SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY",
        "FITHUB_SUPABASE_TABLE",
        "FITHUB_SUPABASE_ROW_ID",
        "FITHUB_SUPABASE_TIMEOUT",
        "FITHUB_SUPABASE_REFRESH_COOLDOWN_SECONDS",
        "FITHUB_SUPABASE_BACKUP_RETENTION",
        "FITHUB_SUPABASE_PRUNE_INTERVAL_SECONDS",
        "FITHUB_MEDIA_STORAGE_PROVIDER",
        "FITHUB_MEDIA_BUCKET",
        "FITHUB_TENCENT_COS_SECRET_ID",
        "FITHUB_TENCENT_COS_SECRET_KEY",
        "FITHUB_TENCENT_COS_REGION",
        "FITHUB_TENCENT_COS_BUCKET",
        "FITHUB_TENCENT_COS_PUBLIC_BASE_URL",
        "FITHUB_IMAGE_UPLOAD_LIMIT_BYTES",
        "FITHUB_VIDEO_UPLOAD_LIMIT_BYTES",
        "FITHUB_THUMB_UPLOAD_LIMIT_BYTES",
        "FITHUB_ADMIN_TOKEN",
        "FITHUB_MEDIA_MAINTENANCE_TOKEN",
    ):
        lines.append(f"{key}={values[key]}")
    return "\n".join(lines) + "\n"


def redact_value(key: str, value: str) -> str:
    if not value:
        return ""
    if key in {"SUPABASE_SERVICE_ROLE_KEY", "FITHUB_ADMIN_TOKEN", "FITHUB_MEDIA_MAINTENANCE_TOKEN", "FITHUB_TENCENT_COS_SECRET_KEY"}:
        return value[:6] + "..." + value[-4:]
    return value


def write_text_securely(path: Path, content: str, *, force: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists. Use --force to overwrite.")
    path.write_text(content, encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def render_nginx_config(api_origin: str, web_origin: str = "") -> str:
    parsed = urllib.parse.urlparse(normalize_origin(api_origin))
    api_host = parsed.hostname or ""
    server_hosts = [api_host]
    if web_origin:
        web_parsed = urllib.parse.urlparse(normalize_origin(web_origin))
        web_host = web_parsed.hostname or ""
        if web_host and web_host not in server_hosts:
            server_hosts.append(web_host)
    server_names = " ".join(server_hosts)
    template = NGINX_TEMPLATE.read_text(encoding="utf-8")
    return (
        template
        .replace("api.yourdomain.com app.yourdomain.com", server_names)
        .replace("api.yourdomain.com", api_host)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate FitHub Tencent Cloud .env.production.")
    parser.add_argument("--api-origin", required=True, help="Production API origin, for example https://api.example.cn")
    parser.add_argument("--web-origin", default="", help="Optional public Web origin, for example https://app.example.cn")
    parser.add_argument("--supabase-url", required=True, help="Real Supabase Project URL.")
    parser.add_argument("--supabase-service-role-key", required=True, help="Real Supabase service_role key.")
    parser.add_argument("--admin-token", default="", help="Optional fixed admin token. Defaults to a generated token.")
    parser.add_argument(
        "--media-maintenance-token",
        default="",
        help="Optional fixed media maintenance token. Defaults to a generated token.",
    )
    parser.add_argument("--media-bucket", default="fithub-media")
    parser.add_argument("--media-storage-provider", default="supabase", choices=["supabase", "cos", "inline"])
    parser.add_argument("--cos-secret-id", default="")
    parser.add_argument("--cos-secret-key", default="")
    parser.add_argument("--cos-region", default="")
    parser.add_argument("--cos-bucket", default="")
    parser.add_argument("--cos-public-base-url", default="")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--print-redacted", action="store_true", help="Print generated values with secrets redacted.")
    parser.add_argument("--nginx-output", default="", help="Optional path to write an Nginx config with the API host filled in.")
    args = parser.parse_args()

    try:
        values = build_env_values(
            api_origin=args.api_origin,
            supabase_url=args.supabase_url,
            supabase_service_role_key=args.supabase_service_role_key,
            admin_token=args.admin_token,
            media_maintenance_token=args.media_maintenance_token,
            media_bucket=args.media_bucket,
            media_storage_provider=args.media_storage_provider,
            cos_secret_id=args.cos_secret_id,
            cos_secret_key=args.cos_secret_key,
            cos_region=args.cos_region,
            cos_bucket=args.cos_bucket,
            cos_public_base_url=args.cos_public_base_url,
        )
        output = Path(args.output)
        write_text_securely(output, render_env(values), force=args.force)
        if args.nginx_output:
            nginx_output = Path(args.nginx_output)
            write_text_securely(nginx_output, render_nginx_config(args.api_origin, args.web_origin), force=args.force)
    except (OSError, ValueError, FileExistsError) as exc:
        print(f"Tencent env init failed: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote production env: {Path(args.output)}")
    if args.nginx_output:
        print(f"Wrote Nginx config: {Path(args.nginx_output)}")
    if args.print_redacted:
        for key, value in values.items():
            print(f"{key}={redact_value(key, value)}")
    print("Next: run python3 scripts/tencent_cloud_preflight.py --env-file " + str(Path(args.output)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
